"""initial

Revision ID: f393ba4ac12c
Revises: 
Create Date: 2025-04-16 18:09:10.303251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f393ba4ac12c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_material', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', mysql.DECIMAL(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###
